/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookTracker.gui;

import com.bookTracker.exception.ValidationException;
import com.bookTracker.model.Genre;
import com.bookTracker.service.BookService;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * Painel de formulário para o cadastro de novos gêneros literários.
 * * Este painel é exibido dentro de um JDialog modal quando o usuário
 * clica em "Cadastrar Gênero" na tela principal.
 * * Responsabilidades:
 * - Receber o nome do novo gênero.
 * - Validar a entrada (não pode ser vazia).
 * - Enviar o novo gênero para o BookService salvar.
 * - Tratar erros de duplicidade (gênero já existente).
 * * @author Netto
 */
public class NewGenre extends javax.swing.JPanel {

    /** Serviço para realizar operações de persistência. */
    private BookService bookService;
    
    /**
     * Construtor do painel NewGenre.
     * * Inicializa os componentes visuais e configura os ouvintes de eventos.
     * * @param bookService A instância do BookService vinda do MainFrame,
     * necessária para salvar o novo gênero no sistema.
     */
    public NewGenre(BookService bookService) {
        initComponents();
        this.bookService = bookService;
        addListeners();
    }
    
    /**
     * Centraliza a configuração dos ouvintes de eventos (listeners) dos botões.
     */
    private void addListeners() {
        cancelButtonGenre.addActionListener(e -> onCancel());
        saveButtonGenre.addActionListener(e -> onSave());
    }
    
    /**
     * Lógica principal executada ao clicar no botão Salvar.
     * * Passos realizados:
     * 1. Coleta o texto digitado no campo de nome.
     * 2. Verifica se o campo está vazio (validação básica).
     * 3. Instancia um novo objeto Genre.
     * 4. Tenta adicionar via BookService (que pode lançar erro se for duplicado).
     * 5. Exibe mensagem de sucesso e fecha a janela, ou exibe mensagem de erro.
     */
    private void onSave() {
        String genreName = inputGenre.getText().trim();

        // 1. Validação de campo vazio
        if (genreName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "O nome do gênero não pode estar vazio.", 
                    "Erro de Validação", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // 2. Tenta adicionar no service
            Genre newGenre = new Genre(genreName);
            bookService.addGenre(newGenre);

            // 3. Sucesso
            JOptionPane.showMessageDialog(this, 
                    "Gênero \"" + genreName + "\" salvo com sucesso!", 
                    "Sucesso", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            // 4. Fecha a janela
            closeWindow();

        } catch (ValidationException ex) {
            // 5. Tratamento de Erro (ex: gênero duplicado)
            // A mensagem da exceção já contém a explicação amigável para o usuário.
            JOptionPane.showMessageDialog(this, 
                    ex.getMessage(), // Mensagem da exceção (ex: "Este gênero já existe.")
                    "Erro", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * Ação do botão Cancelar.
     * Fecha a janela atual sem realizar nenhuma operação de salvamento.
     */
    private void onCancel() {
        closeWindow();
    }
    
    /**
     * Helper para encontrar e fechar a janela (JDialog) que contém este painel.
     * Utiliza {@code SwingUtilities.getWindowAncestor} para achar o componente pai.
     */
    private void closeWindow() {
        // Pega a "janela" (JDialog) que contém este painel (JPanel) e a fecha.
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconPlusGenre = new javax.swing.JLabel();
        textNewGenre1 = new javax.swing.JLabel();
        textNewGenre2 = new javax.swing.JLabel();
        writeNameGenre = new javax.swing.JLabel();
        inputGenre = new javax.swing.JTextField();
        cancelButtonGenre = new javax.swing.JButton();
        saveButtonGenre = new javax.swing.JButton();

        iconPlusGenre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register.png"))); // NOI18N

        textNewGenre1.setFont(new java.awt.Font("Geist", 1, 18)); // NOI18N
        textNewGenre1.setText("Cadastrando ");

        textNewGenre2.setFont(new java.awt.Font("Geist", 1, 18)); // NOI18N
        textNewGenre2.setText("Novo Gênero");

        writeNameGenre.setFont(new java.awt.Font("Geist", 0, 14)); // NOI18N
        writeNameGenre.setText("Digite o Nome");

        cancelButtonGenre.setText("Cancelar");

        saveButtonGenre.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButtonGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButtonGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(writeNameGenre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(textNewGenre2)
                        .addComponent(textNewGenre1)
                        .addComponent(iconPlusGenre)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iconPlusGenre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNewGenre1)
                .addGap(0, 0, 0)
                .addComponent(textNewGenre2)
                .addGap(33, 33, 33)
                .addComponent(writeNameGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(inputGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButtonGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButtonGenre;
    private javax.swing.JLabel iconPlusGenre;
    private javax.swing.JTextField inputGenre;
    private javax.swing.JButton saveButtonGenre;
    private javax.swing.JLabel textNewGenre1;
    private javax.swing.JLabel textNewGenre2;
    private javax.swing.JLabel writeNameGenre;
    // End of variables declaration//GEN-END:variables
}
