/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookTracker.gui;

import com.bookTracker.model.Book;
import com.bookTracker.service.BookService;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * Painel responsável pelo cadastro de novas citações (quotes) para um livro específico.
 * * Este painel é exibido em uma janela modal quando o usuário clica em "Nova Citação"
 * na tela de detalhes do livro.
 * * Responsabilidades:
 * - Receber o texto da citação.
 * - Validar se o texto não está vazio.
 * - Adicionar a citação à lista de citações do objeto Livro.
 * - Persistir a alteração usando o BookService.
 * * @author Netto
 */
public class NewQuote extends javax.swing.JPanel {
    
    /** Serviço para realizar a persistência (salvar o livro atualizado). */
    private BookService bookService;
    
    /** O livro ao qual a citação será vinculada. */
    private Book book;

    /**
     * Construtor do painel de Nova Citação.
     * * Inicializa a interface, preenche os dados visuais do livro (nome e ID)
     * e configura os ouvintes dos botões.
     * * @param bookService A instância do serviço para salvar os dados.
     * @param book O objeto livro que receberá a nova citação.
     */
    public NewQuote(BookService bookService, Book book) {
        initComponents();
        this.bookService = bookService;
        this.book = book;
        
        // Preenche os labels com informações do livro para contexto do usuário
        nameBook.setText(book.getTitle());
        idQuote.setText(book.getId().substring(0, 8) + "...");
        
        addListeners();
    }
    
    /**
     * Centraliza a configuração dos ouvintes de eventos (listeners) dos botões.
     */
    private void addListeners() {
        saveButton.addActionListener(e -> onSave());
        backButton.addActionListener(e -> onCancel());
    }
    
    /**
     * Lógica executada ao clicar no botão Salvar.
     * * Passos:
     * 1. Obtém o texto do campo de entrada.
     * 2. Valida se o campo não está vazio.
     * 3. Adiciona a string à lista de quotes do objeto Book em memória.
     * 4. Chama o método updateBook do serviço para salvar o livro inteiro (com a nova lista) no arquivo.
     * 5. Exibe mensagem de sucesso e fecha a janela.
     */
    private void onSave() {
        String quoteText = inputQuote.getText().trim();
        
        if (quoteText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "A citação não pode estar vazia.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 1. Adiciona a nova citação (String) à lista de citações do livro
        this.book.getQuotes().add(quoteText);
        
        // 2. Salva o objeto LIVRO (que agora contém a nova citação)
        this.bookService.updateBook(this.book);
        
        // 3. Sucesso
        JOptionPane.showMessageDialog(this, "Citação salva!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        closeWindow();
    }
    
    /**
     * Ação do botão Voltar.
     * Fecha a janela sem salvar nenhuma alteração.
     */
    private void onCancel() {
        closeWindow();
    }

    /**
     * Helper para encontrar e fechar a janela (JDialog) que contém este painel.
     * Utiliza {@code SwingUtilities.getWindowAncestor} para achar o componente pai.
     */
    private void closeWindow() {
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text1 = new javax.swing.JLabel();
        idQuote = new javax.swing.JLabel();
        nameBook = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        textInput1 = new javax.swing.JLabel();
        inputQuote = new javax.swing.JTextField();

        text1.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        text1.setText("Nova Citação");

        idQuote.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        idQuote.setText("idAqui");

        nameBook.setFont(new java.awt.Font("Geist", 0, 24)); // NOI18N
        nameBook.setText("nomeDoLivroAqui");

        saveButton.setText("Salvar");

        backButton.setText("Voltar");

        textInput1.setFont(new java.awt.Font("Geist", 0, 14)); // NOI18N
        textInput1.setText("Digite a Citação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textInput1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputQuote, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idQuote)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(nameBook, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addGap(6, 6, 6)
                                .addComponent(backButton)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(idQuote)
                            .addComponent(text1))
                        .addGap(0, 0, 0)
                        .addComponent(nameBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(textInput1)
                .addGap(5, 5, 5)
                .addComponent(inputQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel idQuote;
    private javax.swing.JTextField inputQuote;
    private javax.swing.JLabel nameBook;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel textInput1;
    // End of variables declaration//GEN-END:variables
}
